### PR TITLE
added webhook endpoints

### PR DESCRIPTION
**Pull request by nerdthatnoonelikes**
I added some new webhook endpoints.

### CODE REVIEW

**Comment by Echo-3-1** [comment]
Just structurify them by using proper class like after awaiting do new Webhook(await this.hander.fetch(.....), this.client)

**Comment by Collbrothers** [comment]
Hello! Thank you for your pull request!

I've looked thru your commit and came to the conclusion of not merging, this due to the lack of typing, return types and mainly the way you handle the returned list in the **getGuildWebhooks** method, see [here](https://github.com/EvolveJS/EvolveJS/blob/e64f19d913cb51a912b0346121d88f42ec600d7e/src/Client/API/RestAPI.ts#L65) for an example of how you would do it.

Once again, thank you for pull requesting, and this is just perfect picking, you did a good job :)

**Comment by nerdthatnoonelikes** [comment]
If possible can you review the new commits I made.

**Comment by Echo-3-1** [comment]
Not just that one, all the ones you added should be edited and that's now how array work I said to structurify them, so it'll be like <Array>.push(new Webhook(fetched, this.client));

**Comment by Echo-3-1** [comment]
@nerdthatnoonelikes your pull request has been approved, it'll be merged soon...

**Pull request merged**
